### ISSUE TITLE
Add support for Yosemitech Y4000 sonde

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/ModularSensors#130]
Although the heavy-lifting was done in https://github.com/EnviroDIY/YosemitechModbus (see issue #https://github.com/EnviroDIY/YosemitechModbus/issues/6), there is still work to be done in ModularSensors.

Working in this branch: https://github.com/EnviroDIY/ModularSensors/tree/Y4000sonde

**Comment by aufdenkampe** [comment]
@bschulz1701, 

I am having power brownout issues when attaching other sensors and a radio, even though your power solutions for the Yosemitech stuff is working when standalone (see https://github.com/EnviroDIY/YosemitechModbus/issues/10 and https://github.com/EnviroDIY/YosemitechModbus/issues/11).

Any ideas for a quick fix on how to get power from my 12V battery, which I have for this particular deployment? Would I need a power regulator, rather than just connecting directly to the battery?

**Comment by bschulz1701** [comment]
It depends how tight the tolerances are on the Yosemitech system, they list voltage of 5~12V, they do not say if that is the recommended operating condition, or the absolute maximum, because a fully charged SLA can hit 13.5V, so ideally there would be a converter in between in bring it down to 12V, but my intuition is that it would be ok with a slightly higher range, and that 5~12v is the recommended range (however, there is no documentation which specifies this!) in which case you could connect the battery directly to the sensor, and then just physically wiring that would be the only difficulty.

**Comment by SRGDamia1** [comment]
@aufdenkampe, is this his writing on develop?

**Comment by SRGDamia1** [comment]
The sonde also would be added to the documentation.

**Comment by aufdenkampe** [comment]
@bschulz1701, the brownout issue seems to have gone away with all the fixes in PR #134. 
In the meanwhile, I now have a bunch of these just in case I need them: [Pololu 12V Step-Up/Step-Down Voltage Regulator S18V20F12](https://www.pololu.com/product/2577).

Thanks!
