### ISSUE TITLE
Pass values by references instead of pointers?

### ISSUE THREAD

**Issue by SRGDamia1** [EnviroDIY/ModularSensors#156]
Apparently, the mantra is: "Use references when possible, pointers when needed."  But i'm passing a lot of pointers around...

@bschulz1701 do you know much about this?

**Comment by bschulz1701** [comment]
So I have not spent as much time in true C++ land, I am usually usually closer to C (which may make things a bit different), but in general yes.

In C you generally use pass by value (probably more so in the embedded systems world than the application world) in order to prevent corruption of variables and things of that nature. 

Then when you need something more complex, you can use pass by reference, I have most commonly seen this used to improve performance of simple functions so you can alter your inputs to the function in place instead of allocating additional memory, also if you need to modify multiple values, you might pass them in by value so that you can "return" multiple values, since obviously you can only truly return a single value.

The main time I have seen pointers used is to pass an array as pointer in order to modify that in place, and then doing the same for returning an array by pointer. Also they are used for stuff like linked lists, so you can point a pointer to another address (the next link in the list) and then also times when having the ability to have a null characteristic is important (again, this is mostly in sorting and list structures to indicate the end of tree or graph)
