### ISSUE TITLE
Move more value assignments to initializer lists

### ISSUE THREAD

**Issue by SRGDamia1** [EnviroDIY/ModularSensors#167]
performance bump?  probably very small, if any

**Comment by neilh10** [comment]
@SRGDamia1 I'm curious if you have more thoughts on this - and just wondering could you clarify waht you mean by initializer lists. I guess you left it as a memo to yourself.  
I'm seeing that for low power management #163, the assignments would be better done in setup() instead of automated cpp initializers.
The issue is for low power management that the processor needs to determine if it has enough power to be able to do anything very early on, and if no power should do deep sleep until enough power is determined to be available. Of course if the power demand is too strong, the processor resets, and repeats and wastes any available power.
