### ISSUE TITLE
New Zealand time zone doesn't work

### ISSUE THREAD

**Issue by escaped-echidna** [EnviroDIY/ModularSensors#259]
I have tried to run the ModularSensors 'No Cellular' and 'simple logging' script with a time zone of 12 (Auckland). This gives me a time stamp with an offset of 20 hours, not 12 hours, for some reason.

**Comment by SRGDamia1** [comment]
Do you have your clock set to be in UTC or in local time? All the examples assume your clock is on UTC. If you'd prefer the clock to be in another time zone, you have to change lines 161-165 accordingly.

I'll also test on my end to see what I get.

**Comment by escaped-echidna** [comment]
When I run the PCsync program to set the RTC clock, it correctly sets to UTC time, regardless of the time I have set on my computer. However when I then run the 'simple logging' script it gives the wrong time. Using time zones between -9 and +9 it works, just not for time zones -10, -11, -12 or +10, +11, +12.
![Picture3](https://user-images.githubusercontent.com/34898610/59984526-5e61ee00-967f-11e9-8304-25261f9d918a.png)
![Picture4](https://user-images.githubusercontent.com/34898610/59984527-5efa8480-967f-11e9-9cf2-c8503d3c8ec8.png)

**Comment by SRGDamia1** [comment]
I'm sorry, I haven't gotten a chance to look into this yet.  I will try to get to it this week.

**Comment by SRGDamia1** [comment]
Found the issue!  I wasn't explicitly casting the timezone to a long into before multiplying by 3600 to get from hours to seconds, so once the timezone was bigger than 9 (9.1, actually) it was overflowing and not working.

That PCSync program will always set the clock in UTC.  The sync inside of modular sensors will set the clock to whatever time zone you want (now, even correctly!).

Thank you so much for posting an issue from the other side of the world!  I probably never would have found the problem otherwise.
